# Generated by Django 4.2.7 on 2024-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(default='Others'),
        ),
    ]
