# Generated by Django 5.0.2 on 2024-02-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='BTspeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('waterProof', models.CharField(max_length=255)),
                ('batteryType', models.CharField(max_length=255)),
                ('chargeTime', models.CharField(max_length=255)),
                ('BTVersion', models.CharField(max_length=255)),
                ('BTRange', models.CharField(max_length=255)),
                ('usbCompatability', models.CharField(max_length=255)),
                ('micTech', models.CharField(max_length=255)),
                ('sdCard', models.CharField(max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
