# Generated by Django 5.0.2 on 2024-02-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('generation', models.CharField(max_length=255)),
                ('screen', models.CharField(max_length=255)),
                ('resulotion', models.CharField(max_length=255)),
                ('internalMemory', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('graphicsCard', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('processorSpeed', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('blueTooth', models.CharField(max_length=255)),
                ('wifi', models.CharField(max_length=255)),
                ('usb', models.CharField(max_length=255)),
                ('fingerPrint', models.CharField(max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
