# Generated by Django 5.0.2 on 2024-02-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_resulotion_laptop_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessEarbuds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('waterProof', models.CharField(max_length=255)),
                ('wearingType', models.CharField(max_length=255)),
                ('volumeControl', models.CharField(max_length=255)),
                ('chargingTime', models.CharField(max_length=255)),
                ('playTime', models.CharField(max_length=255)),
                ('batteryCapBud', models.CharField(max_length=255)),
                ('batteryCapCase', models.CharField(max_length=255)),
                ('BTVersion', models.CharField(max_length=255)),
                ('BTRange', models.CharField(max_length=255)),
                ('microphone', models.CharField(max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
