# Generated by Django 5.0.2 on 2024-02-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_smartwatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('bateryCapacity', models.CharField(max_length=255)),
                ('batteryType', models.CharField(max_length=255)),
                ('inputPort', models.CharField(max_length=255)),
                ('outputPort', models.CharField(max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
