# Generated by Django 5.0.3 on 2024-04-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='buildReview',
        ),
        migrations.AddField(
            model_name='review',
            name='genralReview',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='softwareReview',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
