# Generated by Django 4.2.7 on 2024-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_store_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
